apiVersion: services.k8s.aws/v1alpha1
kind: FieldExport
metadata:
  name: {{ .Release.Name }}-mysql-2-host
spec:
  to:
    name: {{ .Release.Name }}-mysql-2-cm
    namespace: {{ .Release.Namespace }} 
    kind: configmap
  from:
    path: ".status.endpoint.address"
    resource:
      group: rds.services.k8s.aws
      kind: DBInstance
      name: {{ .Release.Name }}-mysql-2
