apiVersion: v2
name: mongo-db
description: Chart holder for argo-cd

type: application
version: 0.1.0
appVersion: "0.1.0"

dependencies:
- name: mysql
  version: 0.1.0
  repository: https://storage.googleapis.com/t3n-helm-charts