orion:
  broker:
    db:
      hosts:
        - mongodb
      name: hella_orion
      auth:
        user: root
      existingSecret: hella-orion-secret

  mongo:
    # we want to use the individually deployed mongodb
    enabled: false

  deployment:
    replicaCount: 1
