{{- if .Values.openshift -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-elasticsearch-sa
  labels:
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
{{- end -}}