{{- if .Values.initData.json.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: market-offering-json-create-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "5"
spec:
  containers:
    - name: market-offering-json-create
      #image: python:3
      image: quay.io/openshift/origin-cli:4.9.0
      command:
        - /bin/sh
        - /scripts/entrypoint.sh
      volumeMounts:
        - name: scripts
          mountPath: /scripts
      env:
        - name: OPENSHIFT_SERVER
          valueFrom:
            secretKeyRef:
              name: marketplace-secret
              key: openshiftServer
        - name: OPENSHIFT_TOKEN
          valueFrom:
            secretKeyRef:
              name: marketplace-secret
              key: openshiftToken
        - name: TARGET_NAMESPACE
          value: {{ .Values.initData.targetNamespace | quote }}
  volumes:
    - name: scripts
      configMap:
        name: marketplace-create-offering-json-cm
  restartPolicy: Never

{{- end }}
