---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "kim_ids_connector_app1"
  name: "kim-ids-connector-app1-ext-to-rest-svc"
  namespace: "kim-poc-02"
spec:
  ports:
  - name: "http-9091"
    nodePort: 32391
    port: 9091
    protocol: "TCP"
    targetPort: 9091
  selector:
    app: "kim_ids_connector_app1"
  type: "NodePort"
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "kim_ids_connector_app1"
  name: "kim-ids-connector-app1-ecc-to-rest-svc"
  namespace: "kim-poc-02"
spec:
  ports:
  - name: "http-9096"
    port: 9096
    protocol: "TCP"
    targetPort: 9096
  selector:
    app: "kim_ids_connector_app1"
  type: "ClusterIP"
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "kim_ids_connector_app1"
  name: "kim-ids-connector-app1-kim-rest-svc"
  namespace: "kim-poc-02"
spec:
  ports:
  - name: "http-9099"
    nodePort: 30998
    port: 9099
    protocol: "TCP"
    targetPort: 9099
  selector:
    app: "kim_ids_connector_app1"
  type: "NodePort"
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "kim_ids_connector_app1"
  name: "kim-ids-connector-app1-int-to-rest-svc"
  namespace: "kim-poc-02"
spec:
  ports:
  - name: "http-9092"
    port: 9092
    protocol: "TCP"
    targetPort: 9092
  selector:
    app: "kim_ids_connector_app1"
  type: "ClusterIP"
