kong:
  image:
    repository: quay.io/fiware/kong
    tag: "0.5.3"
    #pullPolicy: Always
    pullPolicy: IfNotPresent

  replicaCount: 1

  autoscaling:
    enabled: false

  env:
    database: "off"
    nginx_worker_processes: "2"
    proxy_access_log: /dev/stdout
    admin_access_log: /dev/stdout
    admin_gui_access_log: /dev/stdout
    portal_api_access_log: /dev/stdout
    proxy_error_log: /dev/stderr
    admin_error_log: /dev/stderr
    admin_gui_error_log: /dev/stderr
    portal_api_error_log: /dev/stderr
    prefix: /kong_prefix/
    log_level: debug
    nginx_proxy_large_client_header_buffers: "16 128k"
    nginx_proxy_http2_max_field_size: "32k"
    nginx_proxy_http2_max_header_size: "32k"
    plugins: bundled, pep-plugin

  customEnv:
    kong_pluginserver_names: pep-plugin
    kong_pluginserver_pep_plugin_start_cmd: /go-plugins/pep-plugin
    kong_pluginserver_pep_plugin_query_cmd: /go-plugins/pep-plugin -dump
    
  plugins:
    goPlugins:
      - pluginName: pep-plugin
  
  ingressController:
    enabled: false
    installCRDs: false

  # Temporary workaround: disable HTTP2 on admin endpoint
  # https://github.com/Kong/kubernetes-ingress-controller/issues/2435
  #admin:
  #  tls:
  #    parameters: []
  
  proxy:
    enabled: true
    annotations: {}
    tls:
      enabled: false
    ingress:
      enabled: false
    route:
      enabled: true
      #host: hella-kong.ki-marktplatz.fiware.dev
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect

  dblessConfig:
    configMap: hella-kong-cm

ar:
  host: "https://ar.isharetest.net"

satellite:
  host: "https://satellite.ki-marktplatz.fiware.dev"
