{{- if .Values.mysql.enabled }}
apiVersion: rds.services.k8s.aws/v1alpha1
kind: DBInstance
metadata:
  name: ai-marketplace-mysql
spec:
  allocatedStorage: {{ .Values.mysql.storage }}
  dbInstanceClass: {{ .Values.mysql.machineType | quote }}
  dbInstanceIdentifier: "ai-marketplace-mysql"
  engine: mysql
  engineVersion: {{ .Values.mysql.version | quote}}
  masterUsername: {{ .Values.mysql.masterUser | quote}}
  masterUserPassword:
    namespace: {{ .Release.Namespace }}
    name: {{ .Values.mysql.existingSecret | quote}}
    key: password
{{- end -}}