---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "kim_datagenerator"
  name: "kim-datagenerator-ext-to-rest-svc"
  namespace: "kim-poc-02"
spec:
  ports:
  - name: "http-9091"
    nodePort: 31391
    port: 9091
    protocol: "TCP"
    targetPort: 9091
  selector:
    app: "kim_datagenerator"
  type: "NodePort"
---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "kim_datagenerator"
  name: "kim-datagenerator-int-to-rest-svc"
  namespace: "kim-poc-02"
spec:
  ports:
  - name: "http-9092"
    port: 9092
    protocol: "TCP"
    targetPort: 9092
  selector:
    app: "kim_datagenerator"
  type: "ClusterIP"
