keyrock:
  statefulset:
    image:
      repository: fiware/idm
      #tag: i4trust-rc8
      tag: 8.3.0
      #pullPolicy: Always
      pullPolicy: IfNotPresent

  db:
    user: root
    password: dbPassword
    host: mysql

  admin:
    user: admin
    password: admin
    email: admin@test.com

  route:
    enabled: true
    routes:
      - tls:
          termination: edge
          insecureEdgeTerminationPolicy: Redirect
  theme:
    enabled: false

  ## Configuration of Authorisation Registry (AR)
  authorisationRegistry:
    # -- Enable usage of authorisation registry
    enabled: true
    # -- Identifier (EORI) of AR
    identifier: "EU.EORI.DECARDEALER"
    # -- URL of AR
    #url: "https://ar.isharetest.net"
    url: "internal"

  ## Configuration of iSHARE Satellite
  satellite:
    # -- Enable usage of satellite
    enabled: true
    # -- Identifier (EORI) of satellite
    identifier: "EU.EORI.FIWARESATELLITE"
    # -- URL of satellite
    url: "https://ishare-satellite-kim-main.apps.fiware.fiware.dev"
    # -- Token endpoint of satellite
    tokenEndpoint: "https://ishare-satellite-kim-main.apps.fiware.fiware.dev/token"
    # -- Parties endpoint of satellite
    partiesEndpoint: "https://ishare-satellite-kim-main.apps.fiware.fiware.dev/parties"

  additionalEnvVars:
    - name: IDM_TITLE
      value: "Car Dealer - Company Portal"
    - name: IDM_DEBUG
      value: "true"
    - name: DEBUG
      value: "*"
    - name: IDM_DB_NAME
      value: kim_car_idm
    - name: IDM_DB_SEED
      value: "true"
    - name: IDM_SERVER_MAX_HEADER_SIZE
      value: "32768"

  ## -- Configuration of local key and certificate for validation and generation of tokens
  token:
    # -- Enable storage of local key and certificate
    enabled: true
    # -- Identifier (EORI) of local organisation
    identifier: "EU.EORI.DECARDEALER"
    # -- String with private key in PEM format
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      MIIJKgIBAAKCAgEAsZoxiMwztGgyt/d5Sy4IYC14VFDzfVz95QA2HuIAvFw5gZw+
      pPIxRSk+eGMZXDxehV9hp+xtQnWki0JnNlthKkVCNwdQB0LYsVULQGup5v5CAL4w
      gmaVOjA9DKVQ24tcNX3Pt/JgZjbosKSxxE3UrwIWkvq66GUJOd4Z5ASVBTy9aRbA
      OBzBP6g8A9MRxpVZW06K8kDdKIoRCYiUE7Bf/HDsrIORbeLdbXiI/KrPRJUmhPKd
      gAThCjAewo3zKYekvkg+D06rkFbcI1oCM4ppy2r9XySaR5fJQnzCUPzdniS8+5gh
      iGvugxViRho4zLbmf/L8yusIV1vLHVFfqRenXeIaHnsJXuuOq6AfuBTbyPnvatJ8
      YAJwLAKPnzj4TenbfuKcxOf/7uoRARzDlEVl8zVLClCwsz4T+Z380gOwhUKaVFa/
      7BC2CqolIRCnC6BdOAYUxdoWa1nCYyCTz2IXZYVGzXrSXaJWZ5coKhiTMfIxvJZX
      1x3LosawdaJLPJN8WYEX4hvMcpxbGJ25oKprqvMFq66e0wxoJoXt/2N8z8gHCn8H
      SNX2qlWe+kolPiuyQ1g59RCbYo5W0ZmN6v6p1Q2H9BBWj7cV61gW67HlDGWj+XfI
      yIAvtkRANeVKzcoj6tjAd7BLonOFtxyQNLT/dCiMWz2O75OkYnZ/0uGtCSMCAwEA
      AQKCAgEAhs6EhNKC+JAS12Ln1XHWd7Jr4IwlleWM7lKvwddIObFDESdYwXj4fwek
      XFrUOBe2o0PX609hS43iXLYFg9Put9gkP4K0cx6BPnFP/hD6wNQDo265gXF+GdHd
      tQiSjGKGli+uCHDYTR2ml9Ya/Oca5dAO9HeOgbGXRC5atqHnvzbwiqDzPGRPJxN6
      omiG2JYqYk0G2IT1mbza28Koqx04bnQEoZmoPKFz85EHYcoBU4xm1YkWlcKeUk5e
      OszmYoKMQMazHIlZXlEf/VFn1FlenkHSmnI9DNSgtm/eSvz09wHp1IsQAO3z99m2
      Y4Gp1XGLGlmFGj02cqDBVrqags3qgeoSotL4RYWIdrf+UuyK0KYyMRNPkNC4DDrW
      wEQkNbvGl7xHNHJi5JU4mTaLXGz8I5kLiL/Qfn94WwnYslQWu7rHo3Ta4Ftzb7p9
      oR5EdepS5eOX0KymO5h8AcJB//jdCDIs4VEKitJVakA4ce0hbNY9cUi6dR9Ug/xr
      ZREPxAxFw8Ud12EAloqFj1I8HOUEhECErG1hw8yctC314UB5K/8DE5Bo0GICJXiX
      l72MjFiY+lVW6mfNydLqo0EAIAvyWdI7CMDmPY4PSPMmnX8NfYNy9VCAc2ATE590
      c252dtRWxQEH01z4FklibZ87cOFzSyrAHXRRkU6rDfzl1YdLaGECggEBAOyz1QcJ
      qdimX0fyMCZ5nbR2pkQkAYvaAzAOJzebhDT6MtITrPhKDTvgUi3ZXucCV2U+fE/z
      rl2CKRKyAHG7vp4KW5SfdzeQ1oezEHTL7gCYsynDjOatVkaqaCspPT3AuKm6ZkCQ
      uAphdniG0yYIhNe7E8tI+mn+mbybqp8ysdFPuPsYMwfw79akbS2vYpDfEt0E638a
      W1RNq1Gil/NTaIbOYx9lEIiks3ezkWef28Xqo0KOoa67Q4Fmnf13jNaPQctG+7oG
      S+1a42z2iXZ+HEUYG4pgWVEAi6FHS4yJhKXrInN0Qb00eX4sOTSfvCGJBNOJv2I6
      /qeWLTxVBb8lD7ECggEBAMAU5PmF2ht0lWXwTngJXpw6XO8M1j7rmlQWmz9TcWb2
      14IH+HA0kR2IjaGUTBUb2f5r0rQWw0iKOfgUgmgTYF+9YDXznbkhsBZgMvnZYBbG
      ilVs5xo/6o7JJhvLB+ob2SKFGnN9Ej3kIZgRWNADg+4TYWNeIBfxjnytBYhpBLlt
      OkdHQAxRgZ0lKmBCZyPz6fPGj/mtKxrksZtiQzjg6oJCWfyqDbe/OMgFn3sLQmRv
      WNP914jCbzxX10m1n49XMa2HLNwuz9YeUUFf6nsJFpCT5CBQ2YYM8L+4CDnrVDuP
      5YzaRVUvloENEJyeWg3gIBRkeVK9w+lshRD6QSv5jxMCggEBAId9oPE4XNrA0UWT
      onBDqTxFtoLGwYPWNYDqeRRhltnkZfbOgHJXoR+nFiNci/Bb7L7td6cka6jm+q/S
      6GIx/7jjYOzAIzPRWpuuqjrRCNmajuPXJe5dRkeI/7vFDWMt0AaHxkQrEs4OYAw5
      0N+yfKgoU/pHOeA2drX5vT8He7W+lrpUbdGb3w3UbRJ7lEYtCtUtHchRw/mLxAck
      tSn5kpmnxiGQblhpPrnENfVFEj5GQ1Gz52TnmIqXvNP7/MhMlHLRnQIs3IVvQ0N6
      E9GZ+oCqfglFgZrWXxbggqRdi2qWH9BKud6eDPVmRxCSZtQjZHnaHY0TC/XOBvLE
      EFgL1OECggEBALut7skMCz+WWz+eXN2WshXORO3iShhylnmhGRH4Ey768zl/VjU0
      d7I2scR2JRze+NJKQjdqombngJqwV3cfr6P8Ytx0a+DvVKGYX1aXGfdHCPVNEkYo
      u6PGUPEJIXOSwEelbGH5i/BjTpvKH1Aojyj5UMgJuSwL/yA84tIVYuNXIYFx0df3
      b8C/BrfFSgfsFOT3V8gqdpqxaASeL3aM9TZPZKOm+P5X3kA6lkhgiP+feFiyh31+
      FbgNUDMaPoyNMuIN2TxOlQ7u0pAhCvgquhyMFHOq68+6JyX8yDTnhocoI6/LucDx
      XYo83MVbSDyUiGPEhHLfLmSOfzpGe5VfI3cCggEASv2jX8QV81nDWf6NjNF/fhOJ
      r0etvx1YdE0eOdJOWs6TpAtB5pIsqGqxRormhqM/+9+sRDBEJ3WcAJszH+8oYSBu
      ak31WsBzsC2n3zUQxQ4FzaxZMXo5f2QCg66FIKu0Wfyy9Ox0vGYIs4Nw3IaGUdPQ
      VpRZsorh2+zgTl8uk78z0xJOSueVoy1g56N70oOplUy7h5bn1retBVzbKDxeknga
      F5Z7sGVtZ/2+AiYQJlEn21GHj75La0EloVYOR3L8qIxHTuXOTgDU85FxQXL8St2c
      f7K7IJlkHzLJ4m6UTBRT/zHgpyV1VcgTwJhGbkiyHrEP27PbjWC2nh8oiM4Ulw==
      -----END RSA PRIVATE KEY-----
    # -- String with certificate (chain) in PEM format
    cert: |
      -----BEGIN CERTIFICATE-----
      MIIGUjCCBDqgAwIBAgIJALTnY4ETe5dOMA0GCSqGSIb3DQEBCwUAMGoxCzAJBgNV
      BAYTAkRFMQ8wDQYDVQQIEwZCZXJsaW4xDzANBgNVBAoTBkZJV0FSRTEWMBQGA1UE
      AxQNRklXQVJFLUNBX1RMUzEhMB8GCSqGSIb3DQEJARYScm9vdC1jYUBmaXdhcmUu
      b3JnMB4XDTIyMTIzMDEzMzUyMFoXDTI3MTIyOTEzMzUyMFowgZ4xCzAJBgNVBAYT
      AkRFMQ8wDQYDVQQIDAZCZXJsaW4xDzANBgNVBAcMBkJlcmxpbjETMBEGA1UECgwK
      Q2FyIERlYWxlcjETMBEGA1UEAwwKQ2FyLURlYWxlcjElMCMGCSqGSIb3DQEJARYW
      b3BlcmF0b3JAY2FyZGVhbGVyLmNvbTEcMBoGA1UEBRMTRVUuRU9SSS5ERUNBUkRF
      QUxFUjCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBALGaMYjMM7RoMrf3
      eUsuCGAteFRQ831c/eUANh7iALxcOYGcPqTyMUUpPnhjGVw8XoVfYafsbUJ1pItC
      ZzZbYSpFQjcHUAdC2LFVC0Brqeb+QgC+MIJmlTowPQylUNuLXDV9z7fyYGY26LCk
      scRN1K8CFpL6uuhlCTneGeQElQU8vWkWwDgcwT+oPAPTEcaVWVtOivJA3SiKEQmI
      lBOwX/xw7KyDkW3i3W14iPyqz0SVJoTynYAE4QowHsKN8ymHpL5IPg9Oq5BW3CNa
      AjOKactq/V8kmkeXyUJ8wlD83Z4kvPuYIYhr7oMVYkYaOMy25n/y/MrrCFdbyx1R
      X6kXp13iGh57CV7rjqugH7gU28j572rSfGACcCwCj584+E3p237inMTn/+7qEQEc
      w5RFZfM1SwpQsLM+E/md/NIDsIVCmlRWv+wQtgqqJSEQpwugXTgGFMXaFmtZwmMg
      k89iF2WFRs160l2iVmeXKCoYkzHyMbyWV9cdy6LGsHWiSzyTfFmBF+IbzHKcWxid
      uaCqa6rzBauuntMMaCaF7f9jfM/IBwp/B0jV9qpVnvpKJT4rskNYOfUQm2KOVtGZ
      jer+qdUNh/QQVo+3FetYFuux5Qxlo/l3yMiAL7ZEQDXlSs3KI+rYwHewS6Jzhbcc
      kDS0/3QojFs9ju+TpGJ2f9LhrQkjAgMBAAGjgcUwgcIwCQYDVR0TBAIwADARBglg
      hkgBhvhCAQEEBAMCBaAwMwYJYIZIAYb4QgENBCYWJE9wZW5TU0wgR2VuZXJhdGVk
      IENsaWVudCBDZXJ0aWZpY2F0ZTAdBgNVHQ4EFgQUBEFpQ9vLqe5bA5v4MV8cCDXQ
      udUwHwYDVR0jBBgwFoAUJB/hBsZhiGQd1NTRNlJwMAXbbIMwDgYDVR0PAQH/BAQD
      AgXgMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggrBgEFBQcDBDANBgkqhkiG9w0BAQsF
      AAOCAgEAjHfcQgHEEBndknjVwnkZu78V5jasjBANwCBIWruk1jSfv3L6mjhLI5h1
      8y38raU/6T09etUUNUOSY8mEIwcs9pfpP0fTM6giYWUJHbasQHqVpzwHQxt+uP4O
      VcDXMqrUCu+DKoN/u+GwwUa+rmhFpdGluiEXPiw0EOJhq2T4FKgBwSWbFMj0MqKu
      02GbF2tq8Zgj+Vio18MYVcdzJd86aP7n2cdURBLKtr7xqIv0Y+/NQXgsD0HnS8Fe
      0jXtXfSJR+IPaNYPN337cqg9oxRrMmegPMF5z2rBT1vGGubWtMOtaS1fwmPYCeZ1
      XC9ZlsNkcInpiprKRshno+q4lIFekOKrOqglkTnt9EpBFEeJeNs4dxiymBYy8C29
      qYE/6RgBq5oYh5rAkAV5t/utFiv/9v/OcdZLqH4QBwBKARb7DDMB+tQtaiS+h8RB
      25Z/tXPlf1JhJsv17ARt2/+WAoD6RtFNyvUbIOPzoRp8dRPKr4H1WyFeKF/ORRII
      w9rNZjJhqJv3QHZddLGZTS77JbmEXOOZOecyUj97m1iKI1mvAZ393MiQA+51KoBm
      V1yJHIx1iND2QCSUjKoVpjcrKZzgw0/Dqp68xqqkYgkhZ8oBsGRXd/uCmbCoomuz
      yQSEwSFBi2GWUnYsO0qIboU6HORJKsXBZEfg0sUjKhh408urDCY=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIFwjCCA6qgAwIBAgIBATANBgkqhkiG9w0BAQsFADB3MQswCQYDVQQGEwJERTEP
      MA0GA1UECBMGQmVybGluMQ8wDQYDVQQHEwZCZXJsaW4xDzANBgNVBAoTBkZJV0FS
      RTESMBAGA1UEAxMJRklXQVJFLUNBMSEwHwYJKoZIhvcNAQkBFhJyb290LWNhQGZp
      d2FyZS5vcmcwHhcNMjIwOTIxMTIwNDUzWhcNMjkxMjIzMTIwNDUzWjBqMQswCQYD
      VQQGEwJERTEPMA0GA1UECBMGQmVybGluMQ8wDQYDVQQKEwZGSVdBUkUxFjAUBgNV
      BAMUDUZJV0FSRS1DQV9UTFMxITAfBgkqhkiG9w0BCQEWEnJvb3QtY2FAZml3YXJl
      Lm9yZzCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANjtrG/NDN2PtA7l
      1fU9U42abgOyMryMRoT3DB/SlOnGcg8JeWEyha4t8znZMduwP7lMUq281rS3pEZf
      R3lUBfXhC5cBUjQDLKlYdVWTVJTTqhhMLwyNrerd4RIVkx5vMgEfObFkJOjCxDR2
      +bFEHLyXwUaFFz8EAUj8kLsphHIuXv3NLSWiKWH2xYVOx1DKxwAZ+dqTueGyeOvi
      QvO5r78uOG9NjwXw46boREKNSleDXpQMEG94gzgZygjdQ1tR3a/0K8QMlgBI12NO
      pa6XL+an5l5iSzB/oYzZguAX0HGumMUvr4zhKiPzgiKyRrFf1mOjEUpgUV9rDH35
      MNv5cjgjFR1CdvPgveZc7zjZWT4786U8NZ6Wa/jRfiPUISykUps3zfsOq2jWNqSz
      u+LSGcoXRcaL0bIjuScQkVaH3BFua4SuU75bifMaZqol/xVA4CONqXkFkihyuqw2
      eu86045w+XiPpZ1NYa+wdE9pR6RBNgb9vG8Po+43TLe0phxbB8eO5Xokpq2Qe9Hx
      NbrF6sI03n/9VQXmIRcaLvtQ+k2a0sPcmMi0s1b5GCqmf13OlWRxTqPWLuKy8i8c
      yiq2q/XVNpZ5UdIf47rkkI8PGLKe6Nzh/uhd0ZCn0t5Hu8nRS7hi/XCfJ+he6QRg
      KCGSXITG0IwjA50gyaFo6c/9VRePAgMBAAGjZjBkMB0GA1UdDgQWBBQkH+EGxmGI
      ZB3U1NE2UnAwBdtsgzAfBgNVHSMEGDAWgBR/813uZ43zu/7iXBl2WsWTuSlmDjAS
      BgNVHRMBAf8ECDAGAQH/AgEAMA4GA1UdDwEB/wQEAwIBhjANBgkqhkiG9w0BAQsF
      AAOCAgEAVgpKfvpk9uyb16VIWs3uksYzgwJyjGqpJ0j9FmTrg4HyrzfXLKlDX09W
      6RaEZ8dVGPugNsLTA/WXWsejWjaj8Ygk8sy5OLQ/qVO9MFEK5muco2O4Au8GjrOM
      x+Y65DMUByHPHPhUhBapUzSz4ho4rpqabHYc0FIq5tmSMweNUG9rcPRMx9//anOc
      4fkw9Rkvl0oMXHBqDeluLVgfN6xuJX8pqZidgvj6P3Zg7dJqj+1RSNuVdfWwDTug
      25p/VAZqKeFY1UrdbRmREQ22tjgw9eH0+8fv4hK5gWfR8U1qNOIBwRAQasUcOs4T
      tot/QakAb/aP753p2wg2prm/pByB2S3uTcuayj6Z8OUYKQwnF6pLa9HwKOObTD6K
      kRP2OlcPQwwNXzZiHs3eiVgAAoyCSc1I1PIKA64iAJXHsFsCHJzBBStrZLdL1Xcx
      GeurZHg7nulEcMZ32JEShxqPsH/YqorO2RzP4XhsUMh7mEHCLMCZHphzjip5kaoi
      y1Q7+Q1/P0kf7yUTCLudp+20Vm5kFcy9zLLggl7EUkru6djv5q2cbPSz0J/NnPjR
      GOFMlCrJ/DjWNJN0Ss/k3rCuhQbzZGyNw1vQCc602VNpJT5N7N9H7tKaZlE89G1k
      oU/RLlGTDpD/RxBX2s9oFiO4yIX5+R2nfKW36uC9f4hiYT6sRvE=
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      MIIGUTCCBDmgAwIBAgIJAOA3HGewsq2PMA0GCSqGSIb3DQEBCwUAMHcxCzAJBgNV
      BAYTAkRFMQ8wDQYDVQQIEwZCZXJsaW4xDzANBgNVBAcTBkJlcmxpbjEPMA0GA1UE
      ChMGRklXQVJFMRIwEAYDVQQDEwlGSVdBUkUtQ0ExITAfBgkqhkiG9w0BCQEWEnJv
      b3QtY2FAZml3YXJlLm9yZzAeFw0yMjA5MjExMTU5MjNaFw0zMjA5MTgxMTU5MjNa
      MHcxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIEwZCZXJsaW4xDzANBgNVBAcTBkJlcmxp
      bjEPMA0GA1UEChMGRklXQVJFMRIwEAYDVQQDEwlGSVdBUkUtQ0ExITAfBgkqhkiG
      9w0BCQEWEnJvb3QtY2FAZml3YXJlLm9yZzCCAiIwDQYJKoZIhvcNAQEBBQADggIP
      ADCCAgoCggIBAJvAjZJxXckYB11eSRHpQKSoHwXaBmp4S6Tn5JZ6mUy4Z7c0oINg
      mcajIXZwXEU3W+rxd40OMVB2CcoYScxsTF7nrN1LIuSnYYL02yq3pqWe1JpZlAA5
      qakI1x6kx3duj8YocmdZlLDSZt699lN6+7rMdahm0Vcy9Ir7sE23oNMDgzMhTCkq
      OzDfElDYRnpuH6eU3tcToAqkBAQ0qVcfmudsTuGpZ4JrrWgacaB9Ef0hENM5IAK3
      7/rpfYDiKr+5j2VMfuUJ2WlhkiHUNt1Y9UfTrW6qLvnXjM8LjhHrzA2nB6zt9nVW
      iq4K36Ci/nsEAgiJj31mvhufmqBU2Q4SXOWVf73v7QM1ObHps5XuCav1Nh/gKcRe
      Qj1a/nFz+IhENVHlmdPUI2f2/5j/R11oaKeOcLIOeMdt9xzAtCaBYwlhwmgQF2/l
      8dbOugcE2PsWS01rPT735hQ+iJNNWM2791ufhPC/dEQpTP36L4JxUeQgUJfmDZCX
      NEZOFEek8gwmJTySIbnE43oHWMixHtAsUFDa+TYDZtkGWGsQFTsRfh79DTcniJcu
      Gm9rYsYCo54870rkzJwDc73LBIL+5mnUUd1utoI94x72FO1bm4nIKCbSUylrwCaX
      4F5K8bSyfZFUVhW1u/nVo7k5cbwviESYnfFrlO9kZIdbCkLIm5vp0RMzAgMBAAGj
      gd8wgdwwHQYDVR0OBBYEFH/zXe5njfO7/uJcGXZaxZO5KWYOMIGpBgNVHSMEgaEw
      gZ6AFH/zXe5njfO7/uJcGXZaxZO5KWYOoXukeTB3MQswCQYDVQQGEwJERTEPMA0G
      A1UECBMGQmVybGluMQ8wDQYDVQQHEwZCZXJsaW4xDzANBgNVBAoTBkZJV0FSRTES
      MBAGA1UEAxMJRklXQVJFLUNBMSEwHwYJKoZIhvcNAQkBFhJyb290LWNhQGZpd2Fy
      ZS5vcmeCCQDgNxxnsLKtjzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
      A4ICAQCQiR/V4p9VDv2/61apgsUWxyRXa4HXPpuxsTWL/8Z2ztgHiHClmHt48q59
      rn3gGbrXj1sMapCawfN7n7gCJAzCOcwZrNdSiHjBkEOgBSTKoiTfMCcrhLaQP6z6
      6pY+ZJlL5BbhkMd95gAua0VL7W3zt4nDvYB1trzoDlIZPuAYVrAm7xB4CuZVdJDW
      7QpNykH6Er58FiRFOMHP+KvPJm3nZVq6hcQ78XQf6Dco55PsZspXmBLMlTZmKKr2
      rpHHdg9ewayQqkCYiRm+Yr6G1tfkKCehKYdz3ORWVfJ+NrwOEQbRfPuDG2YdQo4+
      R7sXeYMJIEzHHXvO59yiZqPuKok839d7kkrZSqkEZXQSvSolXhqNWH3p7IuOX1/P
      ph1jPFZT+RrORbInUwoScPWsK8yh+mYo9h/+QbA/vZeve0/ExrFCUj2BwHa5scnm
      1uororcEuRkFJjDMX4tJOGv9t/C3+kORSKJSgmPmSZ2XM/jLCIhfDWxlpwFNSJJQ
      F69uygJdFZNlo1jl6fG5lrwWNhArnI49WLQrEmjwG/1zUQz5EiDt8GTKFGNBJNxV
      kb2CZS4H8+GB2UK1nsk+Fv9Joc4CFp6LOvXSJ9m8O/9GIfqOwbl12ldN9/9Oyia5
      gty2Gjmr0kunFqqelUzoqMc7Jh/8EPPjVpK3gJUdZM4JlSHZjA==
      -----END CERTIFICATE-----

## Init script for Keyrock
initScript:
  enabled: true
  user:
    - username: "cardealer-operator"
      email: "operator@cardealer.com"
      password: "operator"
    - username: "cardealer-user"
      email: "user@cardealer.com"
      password: "user"

    
  
