ishare-satellite:

  deployment:
    image:
      repository: fiware/ishare-satellite
      tag: 1.2.0
      pullPolicy: Always #IfNotPresent

  route:
    enabled: true
    tls:
      termination: edge
      insecureEdgeTerminationPolicy: Redirect
    certificate:
      issuer:
        kind: ClusterIssuer
        name: letsencrypt-aws-prod

  existingSecretEnvs: satellite-secret

  satellite:
    workers: 2
    logLevel: "debug"

  config:
    id: EU.EORI.FIWARESATELLITE
    key: ""
    crt: ""

    trusted_list:
      - name: FIWARE-CA
        status: "granted"
        validity: "valid"
        crt: |
          -----BEGIN CERTIFICATE-----
          MIIGUTCCBDmgAwIBAgIJAOA3HGewsq2PMA0GCSqGSIb3DQEBCwUAMHcxCzAJBgNV
          BAYTAkRFMQ8wDQYDVQQIEwZCZXJsaW4xDzANBgNVBAcTBkJlcmxpbjEPMA0GA1UE
          ChMGRklXQVJFMRIwEAYDVQQDEwlGSVdBUkUtQ0ExITAfBgkqhkiG9w0BCQEWEnJv
          b3QtY2FAZml3YXJlLm9yZzAeFw0yMjA5MjExMTU5MjNaFw0zMjA5MTgxMTU5MjNa
          MHcxCzAJBgNVBAYTAkRFMQ8wDQYDVQQIEwZCZXJsaW4xDzANBgNVBAcTBkJlcmxp
          bjEPMA0GA1UEChMGRklXQVJFMRIwEAYDVQQDEwlGSVdBUkUtQ0ExITAfBgkqhkiG
          9w0BCQEWEnJvb3QtY2FAZml3YXJlLm9yZzCCAiIwDQYJKoZIhvcNAQEBBQADggIP
          ADCCAgoCggIBAJvAjZJxXckYB11eSRHpQKSoHwXaBmp4S6Tn5JZ6mUy4Z7c0oINg
          mcajIXZwXEU3W+rxd40OMVB2CcoYScxsTF7nrN1LIuSnYYL02yq3pqWe1JpZlAA5
          qakI1x6kx3duj8YocmdZlLDSZt699lN6+7rMdahm0Vcy9Ir7sE23oNMDgzMhTCkq
          OzDfElDYRnpuH6eU3tcToAqkBAQ0qVcfmudsTuGpZ4JrrWgacaB9Ef0hENM5IAK3
          7/rpfYDiKr+5j2VMfuUJ2WlhkiHUNt1Y9UfTrW6qLvnXjM8LjhHrzA2nB6zt9nVW
          iq4K36Ci/nsEAgiJj31mvhufmqBU2Q4SXOWVf73v7QM1ObHps5XuCav1Nh/gKcRe
          Qj1a/nFz+IhENVHlmdPUI2f2/5j/R11oaKeOcLIOeMdt9xzAtCaBYwlhwmgQF2/l
          8dbOugcE2PsWS01rPT735hQ+iJNNWM2791ufhPC/dEQpTP36L4JxUeQgUJfmDZCX
          NEZOFEek8gwmJTySIbnE43oHWMixHtAsUFDa+TYDZtkGWGsQFTsRfh79DTcniJcu
          Gm9rYsYCo54870rkzJwDc73LBIL+5mnUUd1utoI94x72FO1bm4nIKCbSUylrwCaX
          4F5K8bSyfZFUVhW1u/nVo7k5cbwviESYnfFrlO9kZIdbCkLIm5vp0RMzAgMBAAGj
          gd8wgdwwHQYDVR0OBBYEFH/zXe5njfO7/uJcGXZaxZO5KWYOMIGpBgNVHSMEgaEw
          gZ6AFH/zXe5njfO7/uJcGXZaxZO5KWYOoXukeTB3MQswCQYDVQQGEwJERTEPMA0G
          A1UECBMGQmVybGluMQ8wDQYDVQQHEwZCZXJsaW4xDzANBgNVBAoTBkZJV0FSRTES
          MBAGA1UEAxMJRklXQVJFLUNBMSEwHwYJKoZIhvcNAQkBFhJyb290LWNhQGZpd2Fy
          ZS5vcmeCCQDgNxxnsLKtjzAPBgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUA
          A4ICAQCQiR/V4p9VDv2/61apgsUWxyRXa4HXPpuxsTWL/8Z2ztgHiHClmHt48q59
          rn3gGbrXj1sMapCawfN7n7gCJAzCOcwZrNdSiHjBkEOgBSTKoiTfMCcrhLaQP6z6
          6pY+ZJlL5BbhkMd95gAua0VL7W3zt4nDvYB1trzoDlIZPuAYVrAm7xB4CuZVdJDW
          7QpNykH6Er58FiRFOMHP+KvPJm3nZVq6hcQ78XQf6Dco55PsZspXmBLMlTZmKKr2
          rpHHdg9ewayQqkCYiRm+Yr6G1tfkKCehKYdz3ORWVfJ+NrwOEQbRfPuDG2YdQo4+
          R7sXeYMJIEzHHXvO59yiZqPuKok839d7kkrZSqkEZXQSvSolXhqNWH3p7IuOX1/P
          ph1jPFZT+RrORbInUwoScPWsK8yh+mYo9h/+QbA/vZeve0/ExrFCUj2BwHa5scnm
          1uororcEuRkFJjDMX4tJOGv9t/C3+kORSKJSgmPmSZ2XM/jLCIhfDWxlpwFNSJJQ
          F69uygJdFZNlo1jl6fG5lrwWNhArnI49WLQrEmjwG/1zUQz5EiDt8GTKFGNBJNxV
          kb2CZS4H8+GB2UK1nsk+Fv9Joc4CFp6LOvXSJ9m8O/9GIfqOwbl12ldN9/9Oyia5
          gty2Gjmr0kunFqqelUzoqMc7Jh/8EPPjVpK3gJUdZM4JlSHZjA==
          -----END CERTIFICATE-----

    parties:
      - id: "EU.EORI.DEMARKETPLACE"
        name: "DataMarketplace"
        status: "Active"
        start_date: "2021-09-27T00:00:00Z"
        end_date: "2051-09-27T00:00:00Z"
        crt: |
          -----BEGIN CERTIFICATE-----
          MIIGYDCCBEigAwIBAgIJALTnY4ETe5dLMA0GCSqGSIb3DQEBCwUAMGoxCzAJBgNV
          BAYTAkRFMQ8wDQYDVQQIEwZCZXJsaW4xDzANBgNVBAoTBkZJV0FSRTEWMBQGA1UE
          AxQNRklXQVJFLUNBX1RMUzEhMB8GCSqGSIb3DQEJARYScm9vdC1jYUBmaXdhcmUu
          b3JnMB4XDTIyMDkyMTEyMjczNVoXDTI3MDkyMDEyMjczNVowgawxCzAJBgNVBAYT
          AkRFMQ8wDQYDVQQIDAZCZXJsaW4xDzANBgNVBAcMBkJlcmxpbjEZMBcGA1UECgwQ
          RGF0YSBNYXJrZXRwbGFjZTEZMBcGA1UEAwwQRGF0YS1NYXJrZXRwbGFjZTElMCMG
          CSqGSIb3DQEJARYWZGF0YUBraS1tYXJrdHBsYXR6LmNvbTEeMBwGA1UEBRMVRVUu
          RU9SSS5ERU1BUktFVFBMQUNFMIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKC
          AgEAoteZwY3CY4nhn9xFgGXlAo8UAoskTuytIkOMrwugtmcHrGiNPqJhvQJ9oYrh
          qoF77Q/mkiMXC1yj7nEjhrSwagFhF8kq7HOSWGDu5sLFCUcDsbPqB8ztijM9w68t
          vR9WBvpF2rwB/2NNvzW/bIT8VOcFzDBgHomj73gIdgZybhnkwxpY+9GwQUySAXlL
          +aQwp++E87Eki3YU17mXKkT6Sq8Q0uWp3BlhbZU+A0dV36gssVmbmVst0bw874TQ
          zOk72Ed24StzY68LE/D4NUjoFmVC6h4i3YCE1pZaF6E6TzPgzW4ZeVJoMelYkHNH
          2aFwY4ecyUUdzYhyyo6y/v7OWW/xJTs5GnZc/rK4NhswziOQjUA8g5XGGDlWr3oi
          KceVpBkEnCI/iSYyi1KtpHp2NnVugbnoutg6tTDfqsDCfxq9xd5SVrRvF78YRTL7
          bzIWnNcrv7C1JdF2NDdpSaL/G8TRBtoEdJZUY3k/H1aWJeaJJYdRtM8U/6v3rLKC
          bK1IOBd8adc3m2RM++cqcfbCyr+6t1FslWnRihnl/aeAmczpgEQ26e7A+LzWj5Fh
          d6JGISNXxMYuCq2dJwtF8W2v7hijaGUBB/rKTRvsE2WPrcZmfbb6Z360V1dJ5CMW
          r5B8dwLstdMyVEEMAJxIffDhSrAMr9eMPk909ncfEWshcZcCAwEAAaOBxTCBwjAJ
          BgNVHRMEAjAAMBEGCWCGSAGG+EIBAQQEAwIFoDAzBglghkgBhvhCAQ0EJhYkT3Bl
          blNTTCBHZW5lcmF0ZWQgQ2xpZW50IENlcnRpZmljYXRlMB0GA1UdDgQWBBRsVAwK
          XJFe/1GQn2N84JTxkZ13wjAfBgNVHSMEGDAWgBQkH+EGxmGIZB3U1NE2UnAwBdts
          gzAOBgNVHQ8BAf8EBAMCBeAwHQYDVR0lBBYwFAYIKwYBBQUHAwIGCCsGAQUFBwME
          MA0GCSqGSIb3DQEBCwUAA4ICAQCeMHeU0yITdVL04Cg4eLph2M79p86ma3tZwotC
          g1rQJyzErhWHUzu2OdfEEtM1xCl+g6kba4YmYEIokM8clMNIxNmjzhgbsg5AmHoU
          oDYHdHCwAcUN4jTTeaoByzzdCtkgUK5U9stwn+AnXBNB41/nEH7Qz1Z9dZQzufv0
          6E0xZJS33yZhLEM/HRl/fWtHsPryschkHtE97yHH3THEH8+cRyIryAz/TXrB2igI
          CYq6J0CiGsp7sGYtUW7N0vk9Fys6ArR9l+eJF+vaFuxib2A5p9TRXMPIL3vSYTuT
          65zg2VEFSk221+vr9yCWOjuhJwC4rFkLkrelDyZOb572jcvl9Gp+QIqs9yEX/0X5
          ZLfdFzaAtiWXH63GgRgrlsSlrvzKFblc5zSGe1Tr2R2LaYdjokLONyjLpkQzANgO
          fUmvcmGx+F+fG4i7KTG+M1duadqw+ek4tz2Dzze9BbykfE649sa8DP3VrxHQAt/8
          uRRCZAOloVukJgHNhq75lEeevpuk7054LRnNvwHotyCebDGz4+BbegixOXjAW5sr
          CzRJ2yUfre1ymkWTKXVx06Gjh0aVRdehEaxrrX66bIzul6OxwR2JZS9WJ0izBpmG
          2CuCxOL5+HpIDX7jvqaGaKs0gAxoC2lk4Xzs25hkfgseTzUCS1lVoL5GgOJi8k8X
          Isnk7g==
          -----END CERTIFICATE-----
