{{- if .Values.initScript.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: marketplace-app-create-{{ randAlphaNum 5 | lower }}
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "1"
spec:
  containers:
    - name: app-create
      image: mysql:5.7
      command: 
        - /bin/sh
        - /scripts/create.sh
      volumeMounts:
        - name: scripts
          mountPath: /scripts
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: keyrock-secret
              key: dbPassword
        - name: APP_SECRET
          valueFrom:
            secretKeyRef:
              name: keyrock-secret
              key: appSecret
  volumes:
    - name: scripts
      configMap:
        name: marketplace-app-create-cm
  restartPolicy: Never
{{- end }}
