kind: ConfigMap
apiVersion: v1
metadata:
  name: marketplace-app-create-cm
  annotations:
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
    "helm.sh/hook-weight": "1"
data:
  create.sh: |-
    token=$(curl -iL --request POST 'http://keyrock:8080/v1/auth/tokens' \
      --header 'X-Auth-token: ${token}' \
      --header 'Content-Type: application/json' \
      --data-raw '{
        "name": "dennis.wendland@fiware.org",
        "password": "Wz17vZHSH2tTelVFZoab"
    }'  | awk 'BEGIN {FS=": "}/^x-subject-token/{print $2}' | sed -e 's/\r//')

    # check if app already exists
    applicationList=$(curl --location --request GET 'http://keyrock:8080/v1/applications' \
      --header 'X-Auth-token: ${token}')
    if [[ "$applicationList" == *"\"name\":\"Marketplace\""* ]]; then
      exit 1
    fi 


    appid=$(curl --location --request POST 'http://keyrock:8080/v1/applications' \
      --header 'X-Auth-token: ${token}' \
      --header 'Content-Type: application/json' \
      --data-raw '{
        "application": {
          "name": "Marketplace",
          "description": "Keyrock client for the marketplace."
          "redirect_uri": "http://marktplatz.ki-marktplatz.fiware.dev/auth/fiware/callback",
          "url": "http://marktplatz.ki-marktplatz.fiware.dev",
          "grant_type": [
            "authorization_code",
            "refresh_token"
          ]
        }
      }' | jq .application.id | sed -e 's/"//' | sed -e 's/"//') 

    curl --location --request POST 'http://keyrock:8080/v1/applications/${appid}/roles' \
      --header 'X-Auth-token: ${token}' \
      --header 'Content-Type: application/json' \
      --data-raw '{
          "role": {
              "name": "admin"
          }
      }'

    curl --location --request POST 'http://keyrock:8080/v1/applications/${appid}/roles' \
      --header 'X-Auth-token: ${token}' \
      --header 'Content-Type: application/json' \
      --data-raw '{
          "role": {
              "name": "orgAdmin"
          }
      }'

    curl --location --request POST 'http://keyrock:8080/v1/applications/${appid}/roles' \
      --header 'X-Auth-token: ${token}' \
      --header 'Content-Type: application/json' \
      --data-raw '{
          "role": {
              "name": "seller"
          }
      }'

    curl --location --request POST 'http://keyrock:8080/v1/applications/${appid}/roles' \
      --header 'X-Auth-token: ${token}' \
      --header 'Content-Type: application/json' \
      --data-raw '{
          "role": {
              "name": "customer"
          }
      }'