business-api-ecosystem:
  # Values for fiware/business-api-ecosystem Helm Chart
  #
  # Chart values file:
  # ref: 
  #
  # Deployment on FIWARE OpenShift Cluster
  #   *.apps.fiware.fiware.dev
  #


  openshift: true

  ## Marketplace OAuth and IdM configuration
  ##
  oauth:
    # URL of the FIWARE IDM used for user authentication
    #server: https://idp.ai-marketplace.fiware.io
    server: https://login.ki-marktplatz.fiware.dev
    # OAuth2 Client ID of the BAE applicaiton
    clientId: 71049899-b919-4d0f-9303-e5d2fd1bbb90
    # OAuth2 Client Secret of the BAE application
    clientSecret: f7e11746-b84f-4748-86e5-107146e537e2
    # -- Default role: Role to be used if no role is assigned to user (optional)
    defaultRole: seller
    

  ## External URL used to access the BAE frontend (logic proxy)
  ## Should match the host of the Ingress or Route of the Logic Proxy
  ##
  #externalUrl: https://marketplace.ai-marketplace.fiware.io
  externalUrl: https://marketplace.ki-marktplatz.fiware.dev

  ## Configuration for biz-ecosystem-apis component
  ##
  bizEcosystemApis:
    ## Service account
    serviceAccount:
      create: false
      name: bae-sa

    ## Security context
    securityContext:
      ## -- specifies the user UID
      runAsUser: 0
      ## -- specifies the group GID
      runAsGroup: 0
      
    ## port that the APIs container uses
    port: 8080

    ## database configuration for APIs
    db:
      ## host of the database to be used
      host: mysql
      ## password for connecting the database
      password: Wz17vZHSH2tTelVFZoab


      
  ## Configuration for biz-ecosystem-rss component
  ##
  bizEcosystemRss:
    ## Service account
    serviceAccount:
      create: false
      name: bae-sa

    ## Security context
    securityContext:
      ## -- specifies the user UID
      runAsUser: 0
      ## -- specifies the group GID
      runAsGroup: 0

    ## -- deployment specific configuration
    deployment:
      ## -- configuration of the image to be used
      image:
        ## -- BAE RSS image name
        ## ref: https://hub.docker.com/r/fiware/biz-ecosystem-rss
        repository: fiware/biz-ecosystem-rss
        ## -- tag of the image to be used
        tag: v8.0.0
        #tag: v7.8.0
        ## -- specification of the image pull policy
        pullPolicy: IfNotPresent
        #pullPolicy: Always
    
    ## port that the RSS container uses
    port: 8080
    
    ## database configuration for RSS
    db:
      ## host of the database to be used
      host: mysql
      ## URL connection string of the database to be used
      url: jdbc:mysql://mysql:3306/RSS
      ## password for connecting the database
      password: Wz17vZHSH2tTelVFZoab



  ## Configuration for biz-ecosystem-charging-backend component
  ##
  bizEcosystemChargingBackend:
    ## Service account
    serviceAccount:
      create: false
      name: bae-sa

    ## Security context
    securityContext:
      ## -- specifies the user UID
      runAsUser: 0
      ## -- specifies the group GID
      runAsGroup: 0

    ## -- deployment specific configuration
    deployment:
      ## -- configuration of the image to be used
      image:
        ## -- BAE Charging backend image name
        ## ref: https://hub.docker.com/r/fiware/biz-ecosystem-charging-backend
        repository: fiware/biz-ecosystem-charging-backend
        ## -- tag of the image to be used
        tag: v8.0.0
        ## -- specification of the image pull policy
        pullPolicy: IfNotPresent
          
    ## -- PVC configuration for charging backend plugins
    plugins:
      ## -- Enable the PVC for plugins storage
      enabled: true
      ## -- Annotations
      annotations:
        helm.sh/resource-policy: "keep"
      ## -- IDM Admin username
      idmUser: marketplace@ai-marketplace.fiware.io
      ## -- IDM Admin password
      idmPassword: qfBGKoBtdt1Lav3A3wzO
    
    ## port that the charging backend container uses
    port: 8006

    ## payment configuration
    payment:
      ## method: paypal or None (testing mode payment disconected)
      method: paypal

    ## Paypal Oauth2 configuration
    paypal:
      ## Paypal Client-ID
      clientId: ATHrec61cupNwqrSFgARPY5FodDONQgy9P7yenZ7Tnfy34A-av4CpveHdYOJR_lp3GBxAyFZ0T-UuuM5
      ## Paypal Client-Secret
      clientSecret: EMta9AOG9uq_Z1XHzdjnrLul5DHnYwzeMRANNRrG3vF4UFSOQPgr14tSmS0_h_lZ93TJpFTRCTjr6F3M

    ## database configuration for Charging backend (MongoDB)
    db:
      ## host of the database to be used
      host: mongodb
      ## Database name for connecting the database
      database: charging_db
      ## username for connecting the database
      user: charging
      ## password for connecting the database
      password: 1cOX0DkUSZLopOo0u0ld

    ## -- Configuration for backing up the pvcs of the charging backend into a gcs-bucket
    backup:
      ## -- should the backup for file data be enabled
      enabled: false
      ## -- configuration of the image to be used
      #image:
      #  repository: fiware/copy-to-gcs
      #  tag: 0.0.3
      #  pullPolicy: Always
      ## -- prefix to be used for the backup files
      filePrefix: "charging-ai-marketplace"
      ## -- name of the bucket to be used for backup
      bucketName: "gs://fiware-k8s-backups/ai-marketplace"
      ## -- cron schedule for the backup to be executed
      schedule: "0  */6  *  *  *"
      ## -- name of the secret containing the service account to be used for accessing the bucket. The account should be provided in json format and have write permission on the referenced schema
      secretName: "mongodb-gcs-backup"



  ## Configuration for biz-ecosystem-logic-proxy component
  ##
  bizEcosystemLogicProxy:
    ## Service account
    serviceAccount:
      create: false
      name: bae-sa

    ## Security context
    securityContext:
      ## -- specifies the user UID
      runAsUser: 0
      ## -- specifies the group GID
      runAsGroup: 0

    ## -- statefulset specific configuration
    statefulset:
      ## -- configuration of the image to be used
      image:
        ## -- BAE Logic Proxy image name
        ## ref: https://hub.docker.com/r/fiware/biz-ecosystem-logic-proxy
        repository: fiware/biz-ecosystem-logic-proxy
        ## -- tag of the image to be used
        #tag: v8.0.0
        tag: v8.1.0-rc6
        ## -- specification of the image pull policy
        pullPolicy: Always
        #pullPolicy: IfNotPresent
    
    ## openshift specific route definition. Will not work on plain k8s
    route:
      ## -- should the deployment create openshift routes
      enabled: true
      host: marketplace.ki-marktplatz.fiware.dev

      # -- host to be used
      #host: marketplace.apps.fiware.fiware.dev
      #host: marketplace.fiware.io
      # -- tls configuration for the route
      tls:
        termination: edge
        insecureEdgeTerminationPolicy: Redirect
   
      certificate:
        issuer:
          kind: ClusterIssuer
          name: letsencrypt-aws-prod

    ## ingress configuration
    ## OpenShift: oc label namespace marketplace ingress=nginx
    ingress:
      ## should there be an ingress to connect keyrock with the public internet
      enabled: false
      

    ## port that the logic proxy container uses
    port: 8004

    ## Deployment in development or in production
    nodeEnvironment: production

    ## database configuration for Logic Proxy (MongoDB)
    db:
      # host of the database to be used
      host: mongodb
      # Database name for connecting the database
      database: belp_db
      # username for connecting the database
      user: belp
      # password for connecting the database
      password: FHrmEApoPMDG6dMIyX5H

    ## -- elasticsearch configuration
    elastic:
      ## -- indexing engine of logic proxy
      engine: elasticsearch
      ## -- URL of elasticsearch service
      url: elasticsearch-master:9200
      ## -- API version of elasticsearch
      version: 7.5

    ## -- Custom theme configuration
    theme:
      ## -- Enable theme
      enabled: true
      ## -- Name of the theme
      name: KI-Marketplace
      ## -- Size of PVC to be created
      size: 4Gi
      ## Image which holds the theme files
      #image: fiware/bae-ki-marketplace-theme:v0.0.3
      #image: fiware/bae-ki-marketplace-theme:v0.0.4-rc2
      image: fiware/bae-ki-marketplace-theme:v0.0.6
      # -- specification of the image pull policy
      imagePullPolicy: Always
      ## Path to the source theme files inside the container
      #  Files will be copied to /themes/{{name}} with the PVC mounted at /themes
      sourcePath: /bae-ki-marketplace-theme

