## values to be used for deployement in demo namespace
## additional config file is used, since we rely on managed databases there.

source: https://github.com/fiware-ops/ai-marketplace
release: ai-marketplace
destination_namespace: &destination ai-marketplace
branch: &branch main
secretsEnabled: &secretsEnabled false

applications:
  - name: mongodb
    enabled: true
    source_path: applications/mongodb
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml

  - name: aws-dbs
    enabled: true
    source_path: applications/aws-dbs
    source_ref: *branch
    destination: *destination
    managedDatabase: true
    helm_values:
    - values.yaml

  - name: aws-dbs-keyrock
    enabled: true
    source_path: applications/aws-dbs-keyrock
    source_ref: *branch
    destination: *destination
    managedDatabase: true
    helm_values:
    - values.yaml

  - name: elastic
    enabled: true
    source_path: applications/elastic
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
  
  - name: keyrock
    enabled: true
    source_path: applications/keyrock
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
    values:
      keyrock:
        route: 
          host: login.ki-marktplatz.fiware.dev
        
  - name: marketplace
    enabled: true
    source_path: applications/marketplace
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
    values:
      business-api-ecosystem:
        oauth:
          server: https://login.ki-marktplatz.fiware.dev
        externalUrl: https://marktplatz.ki-marktplatz.fiware.dev
        bizEcosystemApis:
          db:
            user: admin
        bizEcosystemChargingBackend:  
          db:
            database: charging_db
            host: mongo.cluster-cifkfl9vchfo.eu-central-1.docdb.amazonaws.com
            user: mongoadmin
        bizEcosystemLogicProxy:
          route:
            host: marktplatz.ki-marktplatz.fiware.dev
          db:
            database: belp_db
            host: mongo.cluster-cifkfl9vchfo.eu-central-1.docdb.amazonaws.com
            user: belp
        bizEcosystemRss:
          user: admin
          url: jdbc:mysql://mysql:3306/RSS
