source: https://github.com/fiware-ops/ai-marketplace
release: ai-marketplace
destination_namespace: &destination ai-marketplace
branch: &branch main

applications:
  # Dont change mongodb name, current orion config relies on it.
  - name: mongodb
    enabled: true
    source_path: applications/mongodb
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
  
  - name: elastic
    enabled: true
    source_path: applications/elastic
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
  
  - name: keyrock
    enabled: true
    source_path: applications/keyrock
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
    values:
      keyrock:
        route:
          routes:
            - host: login.ki-marktplatz.fiware.dev
              tls:
                termination: edge
                insecureEdgeTerminationPolicy: Redirect
              certificate:
                issuer:
                  kind: ClusterIssuer
                  name: letsencrypt-aws-prod

  - name: mysql
    enabled: true
    source_path: applications/mysql
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
        
  - name: marketplace
    enabled: true
    source_path: applications/marketplace
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
    values:
      business-api-ecosystem:
        oauth:
          server: https://login.ki-marktplatz.fiware.dev
        externalUrl: https://marktplatz.ki-marktplatz.fiware.dev
        bizEcosystemLogicProxy:
          route:
            routes:
              - host: marktplatz.ki-marktplatz.fiware.dev
                tls:
                  termination: edge
                  insecureEdgeTerminationPolicy: Redirect
                certificate:
                  issuer:
                    kind: ClusterIssuer
                    name: letsencrypt-aws-prod

