source: https://github.com/wistefan/ai-marketplace
release: ai-marketplace
destination_namespace: &destination ai-marketplace
branch: &branch main
secretsEnabled: &secretsEnabled false
idpHost: &idpHost login.ki-marktplatz.fiware.dev
marketplaceHost: &marketplaceHost marktplatz.ki-marktplatz.fiware.dev

applications:
  # Dont change mongodb name, current orion config relies on it.
  - name: mongodb
    enabled: true
    source_path: applications/mongodb
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
  
  - name: elastic
    enabled: true
    source_path: applications/elastic
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
  
  - name: keyrock
    enabled: true
    source_path: applications/keyrock
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
    values:
      keyrock:
        route: 
          host: *idpHost

  - name: mysql
    enabled: true
    source_path: applications/mysql
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
        
  - name: marketplace
    enabled: true
    source_path: applications/marketplace
    source_ref: *branch
    destination: *destination
    helm_values:
    - values.yaml
    values:
      business-api-ecosystem:
        oauth:
          server: https://*idpHost
        externalUrl: https://*marketplaceHost
        bizEcosystemLogicProxy:
          route:
            host: *marketplaceHost

